# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zX_6k_rW3U05e8BLOc3M-8bmlEGIo2W

Name: Chasitty Ayala
"""

!pip install --upgrade tensorflow transformers datasets sacremoses sentencepiece sacrebleu evaluate huggingface_hub -q

#importing required libraries
import os
import sys
#Transformers and NLP libraries
import transformers
import evaluate
import tensorflow as tf
import numpy as np
import re
import json
import seaborn as sns
import pandas as pd
#For data visualization and plotting
import matplotlib.pyplot as plt

#Hugging Face datasets library
from datasets import load_dataset, DatasetDict

#Hugging Face tokenizers and model classes
from transformers import AutoTokenizer
from transformers import TFAutoModelForSeq2SeqLM, DataCollatorForSeq2Seq
from transformers import AdamWeightDecay
from transformers import MarianMTModel, MarianTokenizer
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

"""https://huggingface.co/Helsinki-NLP


https://huggingface.co/datasets/CohereForAI/aya_collection

"""

#Loading MarianMT model and tokenizer under model_checkpoint

model_checkpoint = {
    "hi": "Helsinki-NLP/opus-mt-en-hi",   # English to Hindi
    "es": "Helsinki-NLP/opus-mt-en-es",   # English to Spanish
    "fr": "Helsinki-NLP/opus-mt-en-fr",   # English to French
    "ar": "Helsinki-NLP/opus-mt-en-ar",   # English to Arabic
    "pt": "Helsinki-NLP/opus-mt-tc-big-en-pt",   # English to Portuguese
}

#Load the public dataset
raw_datasets = load_dataset("CohereForAI/aya_collection", "aya_dataset")
print(raw_datasets)

#load model and tokenizer
def load_model_token(target_lang):
    model_name = model_checkpoint.get(target_lang)

    if not model_name:
        raise ValueError(f"Model for {target_lang} is not available.")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = TFAutoModelForSeq2SeqLM.from_pretrained(model_name)

    return tokenizer, model


#load models for each language pair

tokenizer, model = load_model_token("hi")
tokenizer, model = load_model_token("ar")
tokenizer, model = load_model_token("es")
tokenizer, model = load_model_token("fr")
tokenizer, model = load_model_token("pt")

#PreProcessing the dataset (tokenizing the inputs and targets)

def preprocess_function(examples, tokenizer, max_input_length = 256,max_target_length = 256):
    # Using 'inputs' as the source language text and 'targets' as the target language text
    # You can see this from loading raw_datasets['train'][0] from previously
    inputs = examples["inputs"]
    targets = examples["targets"]

    #Tokenizing the inputs (source language)
    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

    #Tokenizing the targets (target language)
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets, max_length=max_target_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

#Apply pre-process function to the dataset with the loaded tokenizer
tokenized_datasets = raw_datasets.map(lambda x: preprocess_function(x, tokenizer), batched=True)

#Splitting the dataset into train, validation, and test sets
train_test_split = tokenized_datasets["train"].train_test_split(test_size=0.2)

#validation and test
validation_test_split = train_test_split["test"].train_test_split(test_size=0.5)


#Organize the splits
tokenized_datasets = DatasetDict({
    "train": train_test_split["train"],
    "validation": validation_test_split["train"],
    "test": validation_test_split["test"]
})

#Set batch size and learning parameters
batch_size = 16
learning_rate = 5e-5
weight_decay = 0.01
num_train_epochs = 50

#Define data collator
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, return_tensors="tf")

#prepare datasets for training

#Train dataset split
train_dataset = model.prepare_tf_dataset(
    tokenized_datasets["train"],
    batch_size=batch_size,
    shuffle=True,
    collate_fn=data_collator,
)

#Validation dataset split
validation_dataset = model.prepare_tf_dataset(
    tokenized_datasets["validation"],
    batch_size=batch_size,
    shuffle=False,
    collate_fn=data_collator,
)
#Test dataset split
test_dataset = model.prepare_tf_dataset(
    tokenized_datasets["test"],
    batch_size=batch_size,
    shuffle=False,
    collate_fn=data_collator,
)

#Compile the model with the AdamWeightDecay optimizer
optimizer = AdamWeightDecay(learning_rate=learning_rate, weight_decay_rate=weight_decay)
model.compile(optimizer=optimizer)

#Early Stopping Callback
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

#Train the model with early stopping
history = model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=num_train_epochs,
    callbacks=[early_stopping]
)

#Save the fine-tuned model and tokenizer
model.save_pretrained("fine_tuned_model")
tokenizer.save_pretrained("fine_tuned_model")

print("Model and tokenizer saved successfully.")

def load_fine_tuned_model():
    tokenizer = AutoTokenizer.from_pretrained("fine_tuned_model")
    model = TFAutoModelForSeq2SeqLM.from_pretrained("fine_tuned_model")
    return tokenizer, model

#Load the BLEU metric
bleu_metric = evaluate.load('bleu')

#Load translation variations from JSON file
with open('translation_variations.json') as f:
    data = json.load(f)

reference_texts = data.get('reference_texts', {})
synonyms = data.get('synonyms', {})
formal_informal = data.get('formal_informal', {})
punctuation_adjustments = data.get('punctuation_adjustments', {})

#Text normalization function (converts to lowercase, standarizing punctuation and removing extra spaces:)
def normalize_text(text):
    text = text.lower()
    #Remove extra spaces
    text = re.sub(r'\s+', ' ', text)
    #Standardize sentence-ending punctuation
    text = re.sub(r'[.!?]', '.', text)
    #Remove commas
    text = re.sub(r',', '', text)
    #normalize quotes
    text = re.sub(r'[“”]', '"', text)
    #remove leading question marks
    text = re.sub(r'¿', '', text)
    return text.strip()

#Synonym handling function
def handle_synonyms(language, generated_text, reference_text):
    if language in synonyms:
        for word, synonym in synonyms[language].items():
            #Replace only if synonym matches reference
            if synonym in reference_text:
                generated_text = re.sub(rf'\b{word}\b', synonym, generated_text)
    return generated_text

#Formal/Informal handling function
def handle_formal_informal(language, generated_text, reference_text):
    if language in formal_informal:
        for informal, formal in formal_informal[language].items():
            #Replace only if formal/informal word exists in the reference text
            if formal in reference_text or informal in reference_text:
                generated_text = re.sub(rf'\b{informal}\b', formal, generated_text)
    return generated_text

#Adjust punctuation based on variations
def adjust_punctuation(language, generated_text):
    if language in punctuation_adjustments:
        for punct, variations in punctuation_adjustments[language].items():
            for variation in variations:
                #Replace standalone or misplaced punctuation using regex
                pattern = rf'(?<!\w){re.escape(variation)}(?!\w)'
                generated_text = re.sub(pattern, punct, generated_text)
    return generated_text


def post_process_translation(language, text, reference_text):

    #Normalize the text
    text = normalize_text(text)

    #Apply synonym replacements
    text = handle_synonyms(language, text, reference_text)

    #Apply formal/informal adjustments
    text = handle_formal_informal(language, text, reference_text)

    #Adjust punctuation
    text = adjust_punctuation(language, text)

    return text

bleu_score_matrix = []

#Translate and process text
def translate_text(input_text, target_lang):
    #Load model and tokenizer for the specified language
    tokenizer, model = load_model_token(target_lang)

    #Tokenize the input text
    tokenized = tokenizer([input_text], return_tensors='tf')

    #Generate the output text (translation)
    output_tokens = model.generate(**tokenized, max_length=256)

    #Decode the translated output
    translated_text = tokenizer.decode(output_tokens[0], skip_special_tokens=True)
    return translated_text

#Function to evaluate and save translations and BLEU scores
def evaluate_translation(input_text, target_lang, reference_text, file):
    translated_text = translate_text(input_text, target_lang)
    translated_text = post_process_translation(target_lang, translated_text, reference_text)
    reference_text = post_process_translation(target_lang, reference_text, reference_text)

    print(f"Post-Processed Translation in {target_lang.upper()}: {translated_text}\n")
    print(f"Post-Processed Reference in {target_lang.upper()}: {reference_text}\n")

    #BLEU evaluation
    predictions = [translated_text]
    references = [[reference_text]]
    bleu_score = bleu_metric.compute(predictions=predictions, references=references)
    print(f"BLEU Score in {target_lang.upper()}: {bleu_score}\n")

    #Save the translation and BLEU score to a file
    file.write(f"Input: {input_text}\n")
    file.write(f"Translation ({target_lang.upper()}): {translated_text}\n")
    file.write(f"Reference ({target_lang.upper()}): {reference_text}\n")
    file.write(f"BLEU Score: {bleu_score}\n\n")

    return bleu_score['bleu']

#Test translation using fine-tuned model
input_text = input("Enter what you want to translate: ")
target_lang = input("Enter the language you want to translate to (ex: es for Spanish, ar for Arabic, fr for French, hi for Hindi, pt for Portuguese, all for all languages): ")
reference_text = input("Enter the reference text for BLEU evaluation: ")

#Normalize input and reference texts
input_text = normalize_text(input_text)
reference_text = normalize_text(reference_text)

#Open a log file to save translations and BLEU scores
with open("translations_log.txt", "a") as file:
    if target_lang != "all":
        if target_lang in model_checkpoint:
            #Evaluate translation for a single language
            bleu_score = evaluate_translation(input_text, target_lang, reference_text, file)
            bleu_score_matrix.append([bleu_score])
        else:
            print("Language is not available at this time. Please select a different option.")
    else:
        language_scores = []
        for lang in model_checkpoint.keys():
            #Prompt for reference text for each language
            reference_text = input(f"Enter the reference text for BLEU evaluation in {lang.upper()}: ")
            reference_text = normalize_text(reference_text)

            #Evaluate translation for each language
            bleu_score = evaluate_translation(input_text, lang, reference_text, file)
            language_scores.append(bleu_score)

        #Append the scores for all languages in this round to the matrix
        bleu_score_matrix.append(language_scores)

# Data for visualization
data = {
    "Language": ["Hindi", "Spanish", "French", "Arabic", "Portuguese"],
    "BLEU Score": [0.35, 1.0, 1.0, 0.00, 1.0]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Updated input text for minor title
input_text = "Input Text: Hello, how are you?"

# Visualization with minor title
plt.figure(figsize=(10, 6))
bars = plt.bar(df["Language"], df["BLEU Score"], color="skyblue")

# Highlight the highest BLEU score(s)
max_score = df["BLEU Score"].max()
for bar, score in zip(bars, df["BLEU Score"]):
    if score == max_score:
        bar.set_color("green")

# Add text annotations
for bar in bars:
    plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02,
             f"{bar.get_height():.2f}", ha="center", va="bottom")

# Title and labels
plt.title("BLEU Scores for Translations by Language", fontsize=14)
plt.suptitle(input_text, fontsize=10, y=0.96)  # Minor title below the main title
plt.xlabel("Language", fontsize=12)
plt.ylabel("BLEU Score", fontsize=12)
plt.ylim(0, 1.1)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show plot
plt.show()